# Generated by Django 4.2 on 2025-03-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
