# Generated by Django 4.2.10 on 2025-04-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0003_pcbtype_workorder_created_at_workorder_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='product',
            field=models.CharField(max_length=300),
        ),
    ]
