# Generated by Django 4.2 on 2025-06-10 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0004_alter_workorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='completed_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_rework',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='original_work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rework_orders', to='work_order.workorder'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='workorder',
            name='rework_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
