# Generated by Django 4.2 on 2025-06-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0005_add_quantity_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcbtype',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pcbtype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pcbtype',
            name='prefix',
            field=models.CharField(help_text='Item code prefix (e.g., 5YB, 5RS)', max_length=10),
        ),
    ]
