# Generated by Django 4.2 on 2025-06-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0006_alter_pcbtype_code_alter_pcbtype_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcbtype',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
