# Generated by Django 4.2 on 2025-06-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0007_alter_pcbtype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='assembly_barcode',
            field=models.CharField(blank=True, help_text='Generated assembly barcode/serial number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='assembly_duration_seconds',
            field=models.IntegerField(blank=True, help_text='Total assembly time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='assembly_start_time',
            field=models.DateTimeField(blank=True, help_text='When assembly process started', null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when work order was completed', null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='completed_by',
            field=models.CharField(blank=True, help_text='User who completed the assembly', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='component_scan_data',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed component scan information'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='quality_notes',
            field=models.TextField(blank=True, help_text='Quality control notes', null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='scanned_components',
            field=models.JSONField(blank=True, default=list, help_text='List of scanned component barcodes'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='work_order_barcode',
            field=models.CharField(blank=True, help_text='Generated work order barcode', max_length=100, null=True),
        ),
    ]
