# Generated by Django 4.2 on 2025-03-23 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("item_master", "0002_assemblyprocess_scannedpart_assemblylog"),
        ("work_order", "0002_workorder_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssemblyProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("quantity_completed", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.CharField(max_length=100)),
                ("notes", models.TextField(blank=True, null=True)),
                ("current_sensor_index", models.IntegerField(default=1)),
                (
                    "item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assembly_processes_new",
                        to="item_master.itemmaster",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assembly_processes_new",
                        to="work_order.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assembly Process",
                "verbose_name_plural": "Assembly Processes",
            },
        ),
        migrations.CreateModel(
            name="ScannedPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_code", models.CharField(max_length=100)),
                ("sensor_id", models.IntegerField(blank=True, null=True)),
                ("scan_time", models.DateTimeField(auto_now_add=True)),
                ("operator", models.CharField(max_length=100)),
                ("replaced", models.BooleanField(default=False)),
                (
                    "replaced_with",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("replace_reason", models.TextField(blank=True, null=True)),
                ("replace_time", models.DateTimeField(blank=True, null=True)),
                (
                    "assembly_process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scanned_parts",
                        to="assembly.assemblyprocess",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssemblyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("action", models.CharField(max_length=100)),
                ("details", models.TextField()),
                ("operator", models.CharField(max_length=100)),
                (
                    "assembly_process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="assembly.assemblyprocess",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="scannedpart",
            index=models.Index(
                fields=["assembly_process", "sensor_id"], name="asm_part_sensor_idx"
            ),
        ),
    ]
