# Generated by Django 4.2.10 on 2025-04-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode_number', models.CharField(blank=True, max_length=100, null=True)),
                ('completed_at', models.DateTimeField()),
                ('is_rework', models.BooleanField(default=False)),
                ('reworked', models.BooleanField(default=False)),
                ('original_assembly_id', models.CharField(blank=True, max_length=100, null=True)),
                ('zone', models.CharField(blank=True, max_length=100, null=True)),
                ('reworked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('rework_notes', models.TextField(blank=True, null=True)),
                ('_scanned_components', models.TextField(blank=True, null=True)),
                ('_reworked_components', models.TextField(blank=True, null=True)),
                ('_previous_components', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
