# Generated by Django 4.2 on 2025-06-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0002_completedassembly'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly_id', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('operator', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='assemblyoperationlog',
            index=models.Index(fields=['assembly_id', '-timestamp'], name='assembly_as_assembl_c5e549_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblyoperationlog',
            index=models.Index(fields=['action', '-timestamp'], name='assembly_as_action_daac60_idx'),
        ),
    ]
