# Generated by Django 4.2 on 2025-06-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0003_assemblyoperationlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyprocess',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assemblyprocess',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
