# Generated by Django 4.2 on 2025-03-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ItemMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sno", models.IntegerField(unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("Part", "Part"), ("BOM", "Bill of Materials")],
                        max_length=10,
                    ),
                ),
                ("product", models.CharField(blank=True, max_length=100, null=True)),
                ("item_code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
                ("uom", models.CharField(blank=True, max_length=10, null=True)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "u_oper_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("assembly", models.BooleanField(default=False)),
                ("burn_test", models.BooleanField(default=False)),
                ("packing", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("rev_reason", models.TextField(blank=True, null=True)),
                ("rev_no", models.IntegerField(default=0)),
                ("customer_complaint_info", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
