# Generated by Django 4.2.10 on 2025-04-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0004_pcbitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaster',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
