# Generated by Django 4.2 on 2025-06-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0005_itemmaster_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmaster',
            name='quantity',
        ),
    ]
