# Generated by Django 4.2 on 2025-06-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0006_remove_itemmaster_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyprocess',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
