# Generated by Django 4.2 on 2025-06-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0007_assemblyprocess_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyprocess',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scannedpart',
            name='sensor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
