# Generated by Django 4.2 on 2025-06-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0008_assemblyprocess_barcode_number_scannedpart_sensor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyprocess',
            name='current_sensor_index',
            field=models.IntegerField(default=1),
        ),
    ]
